INSERT INTO MEMBER (ID, NAME, PHONE) VALUES (1, 'xml', '010-9912-1234');
INSERT INTO MEMBER (ID, NAME, PHONE) VALUES (2, 'annotation', '010-2333-4321');

INSERT INTO MEMBER_GROUP (ID, NAME, REMARK) VALUES (1, 'Team1', 'Test1 group');
INSERT INTO MEMBER_GROUP (ID, NAME, REMARK) VALUES (2, 'Team2', 'Test2 group');
